[package]
name = "ifsummary"
version = "0.1.0"
authors = ["Jeff Hiner <jhiner@dwelo.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.3"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
